### Get all users
GET http://localhost:8080/api/users
Accept:  application/json

### Get user
GET http://localhost:8080/api/users/1
Accept:  application/json

### Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "pavel_kupcik",
  "email": "kupcik@example.com",
  "password": "password123",
  "firstName": "Pavel",
  "lastName": "Kupcik"
}

### Update user
PUT http://localhost:8080/api/users/65
Content-Type:  application/json

{
  "email": "kupcik46@gmail.com"
}

### Delete user
DELETE http://localhost:8080/api/users/65

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Refresh token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInRva2VuVHlwZSI6IlJFRlJFU0giLCJpYXQiOjE3NjM4OTQwMTcsImV4cCI6MTc2NDQ5ODgxN30.Go2Ih9j6tLOWvRotkONFU1BhUWM2avKlMi45q6hFsuw"
}

### refresh
POST http://localhost:8080/api/admin/rehash-passwords